name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set Playwright Browsers Path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=/usr/lib/playwright" >> $GITHUB_ENV

      - name: Check Playwright Browsers Path
        run: echo "Playwright Browsers Path: $PLAYWRIGHT_BROWSERS_PATH"

      - name: Install Playwright Browsers
        run: sudo yarn playwright install

      - name: Install node packages
        run: yarn

      - name: Check lint
        run: yarn check:lint

      - name: Check prettier
        run: yarn check:prettier

      - name: Build
        run: yarn build
