name: Clear GitHub Actions Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clear Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .cache
            .npm
            .playwright
          key: ${{ runner.os }}-clear-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-clear
