name: Clear GitHub Actions Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Delete Cache Folders
        run: |
          rm -rf node_modules
          rm -rf .cache
          rm -rf ~/.npm
          rm -rf ~/.cache/ms-playwright
          echo "Cache folders deleted."

      - name: Install Dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} install --legacy-peer-deps

      - name: Clean Gatsby Cache
        run: ${{ steps.detect-package-manager.outputs.manager }} run clean

      - name: Confirm Cache Deletion
        run: |
          if [ -d "node_modules" ] || [ -d ".cache" ] || [ -d "~/.npm" ] || [ -d "~/.cache/ms-playwright" ]; then
            echo "Some cache directories still exist."
            exit 1
          else
            echo "Cache directories successfully deleted."
          fi
