name: Clear GitHub Actions Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clear Cache
        run: |
          sudo rm -rf ${{ runner.workspace }}/_actions
          sudo rm -rf ${{ runner.workspace }}/_tool
