name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global url.https://$PAT@github.com/.insteadOf https://github.com/
          npx gh-pages -d ./public -b gh-pages -t $PAT
